esphome:
  name: sensostar
  comment: SensoStar Energy Meter
  platformio_options:
    board_build.arduino.memory_type: qio_opi
  on_boot:
    then:
      - output.turn_on: adc_control  # IO14 HIGH at boot
    
esp32:
  board: esp32-s3-devkitc-1
  flash_size: 8MB
  framework:
    type: esp-idf
    
psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: "ssid"
  password: "password"
  ap:
    ssid: "SensoStar"
  reboot_timeout: 0s  

captive_portal:

logger:
  level: info
  hardware_uart: UART0
  baud_rate: 115200

api:
  encryption:
    key: "key"
    
ota:
  platform: esphome
    
web_server:
  version: 3
  port: 80
    
external_components:
  - source: github://pr#8103
    components: [uart]
  - source:
      type: git
      url: https://github.com/STB3/esphome-sensostar
    components: [ SensoStar_MBus ]

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Amsterdam
    servers: ["0.nl.pool.ntp.org", "1.nl.pool.ntp.org", "2.nl.pool.ntp.org"]

uart:
  - id: uart_mbus
    tx_pin: GPIO39
    rx_pin: GPIO38
    baud_rate: 2400
    parity: EVEN
    rx_full_threshold: 1
    
SensoStar_MBus:
  id: sensostar_id
  uart_id: uart_mbus
  update_interval: 10s

sensor:
  - platform: SensoStar_MBus
    energy:
      name: "SensoStar Energy"
    volume:
      name: "SensoStar Volume"
    power:
      name: "SensoStar Power"
    flow:
      name: "SensoStar Flow"
    temperature_flow:
      name: "SensoStar Flow Temperature"
    temperature_return:
      name: "SensoStar Return Temperature"
    temperature_diff:
      name: "SensoStar Temperature Difference"
      
  - platform: adc
    pin: GPIO1
    id: adc_input_sensor
    name: "SensoStar Battery Level"
    update_interval: never  # Only update manually
    filters:
      - lambda: return x * 3.2; # Vbat is measured via a resistive divider 33k--o--15k

text_sensor:
  - platform: SensoStar_MBus
    status:
      name: "SensoStar Status"

output:
  - platform: gpio
    pin: GPIO14
    id: adc_control
 
script:
  - id: read_adc_script
    then:
      - output.turn_off: adc_control     # Set IO14 LOW
      - delay: 8ms  # wait until the capacitor on the resistive divider is charged
      - component.update: adc_input_sensor  # Trigger ADC read
      - output.turn_on: adc_control      # Set IO14 HIGH

interval:
  - interval: 600s
    then:
      - script.execute: read_adc_script

button:
  - platform: template
    name: "Read battery level now"
    on_press:
      then:
        - script.execute: read_adc_script
